### ISSUE TITLE
command confused:python evaluate_voc.py --help( --num-class)

### ISSUE THREAD

**Issue by Pythonfred** [hfslyc/AdvSemiSeg#10]
Thanks for sharing.i have got a issure about command parameters.
write this`python evaluate_voc.py --help` in terminal,and thers is a optional  `--num-class`

the original code is:`NUM_CLASSES = 21`,i wonder what will happen if i code `NUM_CLASSES = 3` .
what 's the order of  the object .is it random or has a default order?

**Comment by hfslyc** [comment]
Hi, thanks for interested in our work. Since the models were trained on PASCAL VOC dataset, where there are 21 semantic classes (1 for background). For the class order, we follow the standard VOC object indices. You can also see it at https://github.com/hfslyc/AdvSemiSeg/blob/master/evaluate_voc.py#L129-L134

I am wondering why do you want to change the number of classes to 3?

**Comment by Pythonfred** [comment]
Thanks for your reply.
The reason why I  want to change the number of classes to 3 is  i want to  train this model from scrach using another vehicle dataset (or just the voc 2012) which should be segmented only into three parts:person,car and background.
And i wonder does it works if I change the code [https://github.com/hfslyc/AdvSemiSeg/blob/111d5183a966725d70db0368e9ff4f90ce277756/evaluate_voc.py#L155-L167](url) into  below：
```
classes = np.array(('background', 'car'，'person'))
colormap = [(0,0,0),(0.5,0,0),(0,0.5,0)]
cmap = colors.ListedColormap(colormap)#matplotlib.colors.ListedColormap
bounds=[0,1,2]
norm = colors.BoundaryNorm(bounds, cmap.N)
```

**Comment by hfslyc** [comment]
I see. Yeah, it should work. the classes variable in visualization code actually is not used. So only use the partial colormap should work as well.

**Comment by bonbonjour** [comment]
hello, I also want to implement this code in my dataset, i want to know the format of the dataset and groudtruth, when i use my own dataset,it occures some error
