### ISSUE TITLE
What is exactly batch size number in training?

### ISSUE THREAD

**Issue by John1231983** [hfslyc/AdvSemiSeg#13]
You have three losses: loss_seg, loss_Adv and loss_semi. Each loss used batch size of 10. So, what is batch size of combined `loss=loss_seg + alpha *loss_Adv +beta*loss_semi`. Is it still 10 or 30? Thanks

**Comment by hfslyc** [comment]
For the segmentation network, the batch size is 10. However, for discriminator, we have 10 predictions from the segmentation network and 10 gt maps from the unlabeled data.

**Comment by John1231983** [comment]
Yes. So I am wondering about the discriminator network. It combined of two losses. Each loss takes 10 images a batch, so what is the batch size of the combined loss- loss real and loss fake?

**Comment by hfslyc** [comment]
If you want to have a specific number of batch size, I would say 10.
Because in normal GAN training, when we talk about batch size, it's usually
referring to the batch size of the generator, not the discriminator.

**Comment by hfslyc** [comment]
if there is no further question, I'm closing this issue :)
