### ISSUE TITLE
Both loss_adv, and loss_D decreasing. What should I do?

### ISSUE THREAD

**Issue by John1231983** [hfslyc/AdvSemiSeg#16]
Hello, this is not the bug in your code. I just want to ask a question about my code
I used your code in my dataset. I found that both the `loss_adv` and `loss_D` tend to decrease. While the correct trend must be `loss_adv` increases and `loss_D` decrease. What is my problem? Could you give me some suggestions? Thanks

**Comment by hfslyc** [comment]
loss_adv should be inversely proportional to the loss_D if they are seeing the same data. One possibility is that the data you used for training G and D are mismatched (data augmentation/preprocessing etc).

**Comment by John1231983** [comment]
Thanks but I used same data. I  feed data like dcgan did. 
```
for data in enumerate(dataloader):
     images,targets= data
     #Train G
     loss = loss_seg + 0.1 * loss_adv
     ...
     #Train D
     loss_D=loss_D_real+ loss_D_fake
```
     
```

**Comment by John1231983** [comment]
Thanks. I fixed it.
