### ISSUE TITLE
train.py  make_D_label

### ISSUE THREAD

**Issue by bonbonjour** [hfslyc/AdvSemiSeg#17]
hello,  can you please tell me what the [ def make_D_label(label, ignore_mask): ]mean in train.py line 175-179.
thanks

**Comment by John1231983** [comment]
It just converts from a single value (0/1) to a matrix which contains spatial information. The value in the matrix is multiplied by the single value.

**Comment by hfslyc** [comment]
thanks @John1231983 for explaining. close for now if there is no further issue.

**Comment by LeiyuanMa** [comment]
since" ignore_mask_remain = np.zeros(D_out_sigmoid.shape).astype(np.bool)" ,so is the result of make_D_label is determined by gt_label?gt_label is 1 so D_label is a tensor all 1?gt_label is 0 so D_label is a tensor all 0?If it's true,so what's the meaning of ignore_mask_remain?

**Comment by LeiyuanMa** [comment]
@hfslyc

**Comment by hfslyc** [comment]
yeah it's actually all 0. We experimented with different masking loss for the adversarial loss on the unlabeled data, and in the end, we found that the unmasked version is the best. Sorry for the confusion. Will modify the code in the near future for better readability.

**Comment by LeiyuanMa** [comment]
Thanks for your reply.Your work is very interesting~
