### ISSUE TITLE
no module named packaging

### ISSUE THREAD

**Issue by bonbonjour** [hfslyc/AdvSemiSeg#18]
hello, when I try ti run train.py,  an error accurs: ImportError: No module named packaging
i use python2.7  pytorch=0.4.0  cv2=3.4.2
can you please tell me how to solve it 
thanks very much

**Comment by hfslyc** [comment]
@minicv123 you may look at this:
https://github.com/pypa/setuptools/issues/937
or you can simply comment out the version checking lines
