### ISSUE TITLE
Multi gpu training 

### ISSUE THREAD

**Issue by ashkanaev** [hfslyc/AdvSemiSeg#19]
Is't possible to start training in multi gpu mode? seems that it's not possible.
       

> parser.add_argument("--gpu", type=int, default=0,
>                         help="choose gpu device.")

**Comment by hfslyc** [comment]
Hi,

Our code currently doesn't support multi-GPU training. But I think it can be easily implemented.

**Comment by yyangmei** [comment]
@ashkanaev  Have you successfully train in multi gpu? I want to use two gpus. If you have succeed could you tell me how to do it? Thank you so much!
@hfslyc And have you implemented on multi gpus?Thank you~
