### ISSUE TITLE
loss_semi_adv&&loss_adv_pred

### ISSUE THREAD

**Issue by LeiyuanMa** [hfslyc/AdvSemiSeg#20]
It seems loss_semi_adv&&loss_adv_pred alwayes contribute to the network during training,
I understandt that :
loss_adv_pred = bce_loss(D_out, make_D_label(gt_label, ignore_mask))
is using the gt_label,cause the pred is come from labeled data,but
loss_semi_adv = args.lambda_semi_adv * bce_loss(D_out, make_D_label(gt_label, ignore_mask_remain))
why this loss also using the gt_label,the data is come from the trainloader_remain_iter...?

**Comment by hfslyc** [comment]
Hi,

gt_label is simply 1. It's the binary class index that represents gt in the discriminator training. In the semi-supervised loss, we also want to push the unlabeled data's prediction toward the gt distribution.

Hope this explanation help :)

**Comment by LeiyuanMa** [comment]
"With this loss, we train the segmentation network to fool the discriminator by maximizing the
probability of the predicted results being generated from the ground truth distribution"
Is that the meaning of this sentence?

**Comment by hfslyc** [comment]
Yes

**Comment by LeiyuanMa** [comment]
Thank you !
