### ISSUE TITLE
ignore_labels , why 255?

### ISSUE THREAD

**Issue by ecemlago** [hfslyc/AdvSemiSeg#25]
Hi,

Thanks for sharing your code, i find your work very interesting!

I would like to use your work for my research, I have been checking your code, and as far as i understand, you have a function make_D_labels which return a matrix with all values 1 in case they come from GT or 0 when they come from generator.

However, you have an ignore_mask which you use it for assigning some part of D_label matrix to 255 . I do not understand this. Why would you assign 255 to any item of the matrix? Could you explain what i am missing?

Thanks for your help, I appreciate it!

Regards,Ecem

**Comment by hfslyc** [comment]
Hi Ecem,

Thanks for interested in our work and sorry for the late reply. since there are some regions are not labeled by the GT, we do not train the discriminator on these locations. 255 is just an arbitrary number for ignoring loss values.

Hope that clarify your doubts.

**Comment by ecemlago** [comment]
Thanks a lot for your answer, it is very clear now!
