### ISSUE TITLE
D_remain=True?

### ISSUE THREAD

**Issue by ecemlago** [hfslyc/AdvSemiSeg#27]
Hi,

Thanks again for sharing your code, your work is very interesting.

I see in your paper you mention that the discriminator is only trained with labeled data. However, you assign D_remain argument to True. And in the instructions you give in order to train the network for reproducing your results, you do not set it to False. Am i wrong?

Thanks,Ecem

**Comment by hfslyc** [comment]
Hi Ecem,

We do train D with the unlabeled data. But the difference is quite small.

**Comment by ecemlago** [comment]
Hi!

Thanks a lot for the answer!
