### ISSUE TITLE
ModuleNotFoundError: No module named 'copy_reg'

### ISSUE THREAD

**Issue by John1231983** [hfslyc/AdvSemiSeg#3]
Thanks for sharing your work. I used evaluate code and I got the error
```
    import copy_reg
ModuleNotFoundError: No module named 'copy_reg'
```
I am using python 3.6 from conda install, Ubuntu 16.04. How can I fix it? Thanks

**Comment by hfslyc** [comment]
Hi,

Thanks for interested in our work. Our project was develop using python2.7. Could you switch to python2? In the meantime, I will check what is the potential issue with python3.

**Comment by John1231983** [comment]
Thanks . I fixed it. Just used
```
import copyreg
copyreg.pickle(types.MethodType, _pickle_method)
```
For `advFull`, I got `meanIOU: 0.7491224203274405`. Does it as expected?

**Comment by hfslyc** [comment]
Yes, it's the model that we reported in the paper. If there is no further question, I'm closing this issue :)

**Comment by OlegS1978** [comment]
> Thanks . I fixed it. Just used
> 
> ```
> import copyreg
> copyreg.pickle(types.MethodType, _pickle_method)
> ```
> For `advFull`, I got `meanIOU: 0.7491224203274405`. Does it as expected?

John, could you tell where exactly you fixed it? Or just drop piece of code that you fixed?

**Comment by jefflgaol** [comment]
> > Thanks . I fixed it. Just used
> > ```
> > import copyreg
> > copyreg.pickle(types.MethodType, _pickle_method)
> > ```
> > 
> > 
> > For `advFull`, I got `meanIOU: 0.7491224203274405`. Does it as expected?
> 
> John, could you tell where exactly you fixed it? Or just drop piece of code that you fixed?

Inside AdvSemiSeg-master/utils/metric.py, you need to replace copy_reg with copyreg. I guess you were using Python 3, and if you do, you might also need to change xrange into range.
