### ISSUE TITLE
Some questions I would like to ask you

### ISSUE THREAD

**Issue by watchmexiang** [hfslyc/AdvSemiSeg#31]
Hello, I am planning to use your data to run your network but it fails. My data is in two categories. One is for the background and the other is set to 0 and 1, respectively. For the single channel label map, use your The network has been trained, but the test result output is all 0. May I ask if I need to adjust some parameters, thank you

**Comment by Yuyiba** [comment]
> Hello, I am planning to use your data to run your network but it fails. My data is in two categories. One is for the background and the other is set to 0 and 1, respectively. For the single channel label map, use your The network has been trained, but the test result output is all 0. May I ask if I need to adjust some parameters, thank you

do you have solve this problem?

**Comment by watchmexiang** [comment]
Sorry, I still have to solve this problem. Have you encountered the same problem yet?

**Comment by watchmexiang** [comment]
I think there may be a problem with the amount of data or the learning rate. I am still debugging further. If you are studying this program, we can discuss it further.

**Comment by Yuyiba** [comment]
> I think there may be a problem with the amount of data or the learning rate. I am still debugging further. If you are studying this program, we can discuss it further.

我也没有……这段时间没搞这个了……

**Comment by hfslyc** [comment]
I would suggest train a plain segmentation network without any adversarial loss. The issue doesn't sound like an adversarial learning problem.
