### ISSUE TITLE
difference between SEMI_START and SEMI_START_ADV

### ISSUE THREAD

**Issue by YiruS** [hfslyc/AdvSemiSeg#32]
Hi there,

First, impressive work! 

I'm reading your code but find one uncertain part: what's SEMI_START and SEMI_START_ADV represented for? I know it's used during training semi to determine the #iterations starting training. However in the original code, SEMI_START=5000 and SEMI_START_ADV=0, which means that semi is trained at the very FIRST iteration. Is that a bug since in the paper you mentioned "we start semi-supervised learning after training for 5000 iterations with labeled data"?

Any comments are appreciated!

**Comment by hfslyc** [comment]
Hi,

Thanks for pointing out the typos. Yes, we start adv-semi at the first iteration. But for the self-learning, it needs some iterations to have better prediction. You can also set SEMI_START_ADV to 5000, and it shouldn't make much difference.

**Comment by YiruS** [comment]
> Hi,
> 
> Thanks for pointing out the typos. Yes, we start adv-semi at the first iteration. But for the self-learning, it needs some iterations to have better prediction. You can also set SEMI_START_ADV to 5000, and it shouldn't make much difference.

Thanks for the reply. Another very import question on augmented labels. I noticed that they're only binary for boundaries of the objects. Any specific reason for using it? Or could I skip them and directly train the model? Thanks!

**Comment by hfslyc** [comment]
I'm not exactly sure what's the problem. But on the augmented dataset the boundaries labels should be ignored.
