### ISSUE TITLE
大佬你好，训练的时候出现这个问题了，这是啥情况啊

### ISSUE THREAD

**Issue by wangshicr7** [hfslyc/AdvSemiSeg#35]
loss_semi_adv_value += loss_semi_adv.data.cpu().numpy()[0]/args.lambda_semi_adv
IndexError: too many indices for array

**Comment by hfslyc** [comment]
This repo was using Pytorch 0.2, which has a different behavior than recent version on single scalar. You could remove the [0] and it should work.

**Comment by gxwangupc** [comment]
> loss_semi_adv_value += loss_semi_adv.data.cpu().numpy()[0]/args.lambda_semi_adv
> IndexError: too many indices for array

hahhahahha
