### ISSUE TITLE
Questions about ignore_mask = (y.numpy() == 255) ?

### ISSUE THREAD

**Issue by sunshineymt** [hfslyc/AdvSemiSeg#37]
Hello, first of all, thank you for sharing your work. I have a question in the process of looking at the code.ignore_mask = (y.numpy() == 255)  Can you explain this to me? If my label y has a value of 0-9, can it be written like this? I look forward to your reply. Thank you very much.

**Comment by hfslyc** [comment]
Hi,

For some dataset (e.g., PASCAL), there are some boundary pixels are labeled as 255 (ignored). If your dataset doesn't have this scenario. It should be ok to directly apply the code

**Comment by sunshineymt** [comment]
Thank you for your answer. I still want to ask a question, is the discriminator network or formula? I mainly want to ask about the process of confrontation, can you roughly tell me about it?  I have been unable to understand this point, look forward to your answer, thank you!

**Comment by tuscasp** [comment]
It is a network, as it is explained in the article about this implementation:

> Discriminator network. We use the structure similar to [38] for the discriminator network.
It consists of 5 convolution layers with 4×4 kernel and {64, 128, 256, 512, 1} channels in
the stride of 2. Each convolution layer is followed by a Leaky-ReLU [30] parameterized
by 0:2 except the last layer. To transform the model into a fully convolutional network, an
up-sampling layer is added to the last layer to rescale the output to the size of the input map.

**Comment by hfslyc** [comment]
If there is no further question, I will close this issue for now. Thanks @tuscasp for the explanation.
