### ISSUE TITLE
some question of the code

### ISSUE THREAD

**Issue by kukby** [hfslyc/AdvSemiSeg#42]
Hello,thanks for your work. In your article ,you said your remove the last classification layer and use the Atrous Spatial Pyramid Pooling method in the last layer. But in your deeplab.py, it use the classification_module and no mention to the ASPP method. I can not understand why?Can you replay me?...please

**Comment by bomtorazek** [comment]
I think 
        for dilation, padding in zip(dilation_series, padding_series):
            self.conv2d_list.append(nn.Conv2d(2048, num_classes, kernel_size=3, stride=1, padding=padding, dilation=dilation, bias = True))
means ASPP
