### ISSUE TITLE
how to run on cpu

### ISSUE THREAD

**Issue by wwwmmmqqq** [hfslyc/AdvSemiSeg#48]
raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

How can i run it on cpu.Hlep me,please.Thank you!

**Comment by yutaroyamanaka** [comment]
I think training is impossible without GPUs

**Comment by colindecourt** [comment]
> I think training is impossible without GPUs

Yes, it doesn't work. Your computer can run the code (if you remove all dependencies to cuda) but the training will take too much time and I think your computer will crash.

**Comment by wwwmmmqqq** [comment]
oh,god.I got it,thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Colin Decourt"<notifications@github.com&gt;; 
发送时间: 2019年12月27日(星期五) 晚上8:09
收件人: "hfslyc/AdvSemiSeg"<AdvSemiSeg@noreply.github.com&gt;; 
抄送: "W"<1059257750@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hfslyc/AdvSemiSeg] how to run on cpu (#48)



 
I think training is impossible without GPUs
  
Yes, it doesn't work. Your computer can run the code (if you remove all dependencies to cuda) but the training will take too much time and I think your computer will crash.

**Comment by hfslyc** [comment]
Thanks for the replies guys! Close this issue for now.
