### ISSUE TITLE
train.py running error

### ISSUE THREAD

**Issue by lapetite123** [hfslyc/AdvSemiSeg#6]
hi, thanks for your work.
when i run train.py, the error occurs : file"train.py",line 375,in main 
  loss_seg_value+=loss_seg.data.cpu( ).numpy()[0]/args.ier_size   
 indexError: too many indices fro array 

i don't know how to solve it ,please help me

**Comment by John1231983** [comment]
this error comes from 0.4. to fix it, delete all [0] in train.py

**Comment by hfslyc** [comment]
thanks @John1231983 . This repo was developed under Pytorch 0.2/0.3. We will update the code to support Pytorch 0.4.

**Comment by lapetite123** [comment]
thank you very much! I have solved it
