### ISSUE TITLE
Not able to reach pre-trained models

### ISSUE THREAD

**Issue by vikolss** [hfslyc/AdvSemiSeg#67]
Hi,
Thanks for the excellent code!
I am no longer able to reach the pre-trained models, in particular the pretrained COCO model 'http://vllab1.ucmerced.edu/~whung/adv-semi-seg/resnet101COCO-41f33a49.pth', which is referenced in [here](https://github.com/hfslyc/AdvSemiSeg/blob/841d546c927605747594be726622363bf781cefb/train.py#L47). 
Is there anywhere else that this pre-trained model can be downloaded?

Thanks

**Comment by auguser** [comment]
hi，did you solve it？

**Comment by vikolss** [comment]
Yes, the model can be found at another URL, see this [issue](https://github.com/vikolss/DACS/issues/15).
