### ISSUE TITLE
关于5000次迭代前的训练

### ISSUE THREAD

**Issue by lijiwen97** [hfslyc/AdvSemiSeg#68]
您好，您的论文里提到：先用有标签数据迭代5000次再开始半监督训练。那为什么在代码中一开始就用了无标签数据（#do semi first）做了loss_semi_adv。

**Comment by xiewende** [comment]
the same problems，how to explain this？

**Comment by lijiwen97** [comment]
目前没有解开这个疑惑，您能提供您训练的代码给我参考下吗？万分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hfslyc/AdvSemiSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 晚上10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hfslyc/AdvSemiSeg] 关于5000次迭代前的训练 (Issue #68)





 
the same problems，how to explain this？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiewende** [comment]
i just use this repo code
