### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Pythonfred** [hfslyc/AdvSemiSeg#9]
Thanks for sharing your work. I used evaluate code and I got the error.Here is the detail:

> Traceback (most recent call last):
>   File "evaluate_voc.py", line 236, in <module>
>     main()
>   File "evaluate_voc.py", line 210, in main
>     for index, batch in enumerate(testloader):
>   File "C:\Users\landlord\Anaconda3\envs\aa\lib\site-packages\torch\utils\data\dataloader.py", line 264, in __next__
>     batch = self.collate_fn([self.dataset[i] for i in indices])
>   File "C:\Users\landlord\Anaconda3\envs\aa\lib\site-packages\torch\utils\data\dataloader.py", line 264, in <listcomp>
>     batch = self.collate_fn([self.dataset[i] for i in indices])
>   File "E:\AdvSemiSeg-master\dataset\voc_dataset.py", line 58, in __getitem__
>     img_h, img_w = label.shape
**> AttributeError: 'NoneType' object has no attribute 'shape'**

    
I am using python 3.6 from conda install, win10. How can I fix it? Thanks

**Comment by Pythonfred** [comment]
i have fixed it. i delete others files  under 

> /dataset/voc2012/ 

to make the file structure just like you said.

**Comment by xysaber** [comment]
> i have fixed it. i delete others files under
> 
> > /dataset/voc2012/
> 
> to make the file structure just like you said.

hello,I face the same issue and I want to ask which files should be deleted in the files to make the datasets right in training? Thank you
